/*Provider bindings are generated by running cdktf get.
See https://cdk.tf/provider-generation for more details.*/
import { SpotifyProvider } from "./.gen/providers/spotify/provider";

// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0
import { Construct } from "constructs";
import {
  App,
  TerraformStack,
  Token,
  CloudBackend,
  NamedCloudWorkspace,
} from "cdktf";

import { MyPlaylist } from "./util";

class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    // Provider Setting
    require("dotenv").config(); // .env を読み込み
    new SpotifyProvider(this, "spotify", {
      apiKey: Token.asString(process.env.SPOTIFY_PROXY_API_KEY),
    });

    // Backend Setting
    new CloudBackend(this, {
      hostname: "app.terraform.io",
      organization: "grandcolline",
      workspaces: new NamedCloudWorkspace("spotify-playlist"),
    });

    // Playlist

    MyPlaylist(this, "up", {
      name: "🤘 テンションぶちあげ",
      description: "とにかくノリたいときに🕺",
      tracks: [
        "1lQWhRQ1JoPmIsVYZhDiCD", // Listen Up (1985) / Passion Pit
        "3AA8xNhDC0MpqwkGX3EP5V", // If I Ever Feel Better / Phoenix
        "1kSiGrc3GAOWLnLuLlHh0e", // Easy / Tahiti 80
        "39EISCnBUBzbDxBtaOCyPD", // Dance With Somebody / Mando Diao
        "0zz9Y8cDtiIe56XpG73vJy", // Groria / Mandodiao
        "1BiRaCcUqWpLLb4LZpvRMF", // If You Ever Leave, I'm Comming With You / The Wombats
      ],
    });

    MyPlaylist(this, "citypop", {
      name: "🌃 おしゃシティポップ",
      description: "いま流行りのChillとやらをする曲たち🌛",
      tracks: [
        "3O4SdpqF7RzZkA79cRBvwV", // Climax Night / Yogee New Waves
        "3qAT9iw2AiiJ0CxTcqxQn1", // ヒットナンバー - EVISBEATSとPUNCH REMIX / おかもとえみ
        "75HcneiRhhR7rSz9wNp5I3", // 202 feat. 泉まくら / ラブリーサマーちゃん
        "1PQzEVA6AtkAkJTS28RJD8", // 80 denier / kiki vivi lily
        "2YACdk3xERwvxuT0JUBxvy", // BLUE feat. kojikoji (Acoustic) / LUCKY TAPES
        "5MUtNMkyc3wG8k4Zwzdvmv", // Buddies / ZIN
        "2mrT7SZff7rpWppD9C8XEQ", // CALL ME IN YOUR SUMMER / SHE IS SUMMER
        "5cAEkJEYiNTO26oXRKnxJn", // Contact - TOSHIKI HAYASHI(%C) remix / 鈴木真海子
        "7kBSLhGehCNcUJMpTUWkO9", // For ten minutes, for a hundred yen / MAISONdes
        "6uSe3ACORUIVrAyiP84RZi", // melt bitter / さとうもか
        "7I8UsN16TuLIv1NctuVShw", // POOL - (gappy ver.) / おかもとえみ
        "5b6ZcC3q855F3Sv1rV9jsF", // Rainbow Town - SUKISHA
        "7bQKZTYbOdpJLICtehCBCz", // spacecraft / sui sui duck
        "2YfE0VF7XENPWTf7hP6TQU", // Summer Gate / 佐藤千亜妃
        "7E0HrAjY5imdytUxy8Nerf", // Sweet and Sour / Nulbarich
        "6Mavd9uk89Y9OTdvcDTfGG", // クロノスタシス - きのこ帝国
        "5woQHWA238n9vsaCxehJMa", // サーカスナイト - 七尾旅人
        "1nzgVwPzKY8V4RcMK7AvaC", // ラビリンス'97 / chelmico
        "2fHKfpwuo4gioZajag3N7T", // 兄弟 feat. クボタカイ / Mega Shinnosuke
        "1cr5cFqUzUPYVLM0s3xHkv", // 君はQueen / ぷにぷに電機
        "0ZQ9oSwoUAbrOGMoUDUJwf", // 夏の魔法 / Enjoy Music Club
        "6XwsccSztaHfssOmwUmR1c", // 夜の探検 / chilldspot
        "5RbV7Ps6HM2tBbxTd3FnDh", // 水星 / daoko
      ],
    });

    MyPlaylist(this, "idol_2020", {
      name: "🎤 アイドルソング2020",
      description:
        "個人的な独断と偏見に満ちた2020年のアイドルソングのベスト10曲",
      tracks: [
        "3k9WcHPr33PMiikGxRyrso", // untie / sora tob sakana
        "6jMqb8DaeiD6ZZTFDCYytA", // ゆめをみる / 根本凪
        "4mZYwndiM9L7uQlyzWdTnx", // 再逢い / 963
        "7qBGMMt5oXeDRpA6lvG88P", // sekisyo / nuance
        "6NRTJsFSssuOXz19AjL63V", // 朝になれ / 加納エミリ
        "50i41IVm0YCEdZ2wpHi5MF", // ノンフィクション / NELN
        "4gJTvGUAY17WN8r7heccoj", // こころ盗んで / 奥津マリリ
        "3KD3C7dwO95PPzQXQifft8", // 春にゆびきり / RYUTist
        "27FOGkwF96dWrfjBtXs78r", // ヒアルロンリーガール / ZOC
        "4kwTBNoFgxKWounDvAgFtT", // Dancer in the Night / ばってん少女隊
      ],
    });

    MyPlaylist(this, "idol_2021", {
      name: "🎤 アイドルソング2021",
      description:
        "個人的な独断と偏見に満ちた2021年のアイドルソングのベスト13曲",
      tracks: [
        "2kWnEqjiLZKHnKBfPvDqi2", // 深海 / fishbowl
        "6hvaKToIxRW1wJQMcT6bYH", // わたし、恋始めたってよ / ばってん少女隊
        "2Z7Kpoh85XBTrCmsYfdSmg", // 水硝子 / RYUTist
        "4bfajV2uBsIORZdANZZNwe", // REM / NELN
        "5SXfrdgEbI7dN1NYRtTYFI", // Secret Summer / 開歌
        "2l0gIK1rMEDPuQUCCZ32yk", // 根も葉もRumor / AKB48
        "0j7N2tCclKzN8oW2rbW2iU", // Nichijo / ピューパ!!
        "2vMLuzEFT4pbA8Ih4uFvD7", // 観月京 / きのホ。
        "03sd4RARpMXsXqiGLRnxqX", // ファーストキッスは竜人くん / ねもぺろ
        "6etFSn4PmCKt0SYrdU7eJT", // クロックワーク・スパークル / tipToe.
        "1qFW5JX6JucWQCPthalaSn", // フォークソング / リルネード
        "190fjpD9ZRqtuwRSOJZAcQ", // 抱えきれないわ / SAKA-SAMA
        "4hHESNOgRzQq9QaMSXCmjp", // LastSummer Girl / カナミル
      ],
    });

    MyPlaylist(this, "idol_2022", {
      name: "🎤 アイドルソング2022",
      description:
        "個人的な独断と偏見に満ちた2022年のアイドルソングのベスト12曲",
      tracks: [
        "3DR2RbatuGm3UVMrFflZxM", // わたしの一番かわいいところ / FRUITS ZIPPER
        "0TQpPhA1OBrVGIfaKShRrx", // femme fatal / だいしきゅーだいしゅき
        "1pkrnrxkcUGnCOQmhU7DnG", // ハジマリズム / ジョナゴールド
        "0UqogR4fQoXiClzRibMMSx", // 旬をすすめ / さよならステイチューン
        "29WVraNo2Gcd8BtTYlA5ox", // シュガーゲーム / ステラシュガレット
        "0Yh8KpL8Iu733TRiUILNup", // 蜃気楼 / タイトル未定
        "5EyoUNX0NkkotkTD3cL8aE", // さがしもの / ばってん少女隊
        "5TDU6FxtwdFzLvNgO0XAkj", // パルス / Ringwanderung
        "61jpOEFOyTfHFh9N3WDc2E", // きらめき、いま、見えるでしょ / リルネード
        "0lWgp9d6pQExx2lRptw10s", // 税金なんてわかんない / NELN
        "7g4bY7cvUAYw3lBUMfNz1T", // uragaeshi / llie
        "2g9Mfn7o9IxJ6kmtHa9IXn", // ネガティブ・グライダー / SAKA-SAMA
      ],
    });
  }
}

const app = new App();
new MyStack(app, "cdk");
app.synth();
